language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: "./manage.py test"

notifications:
  email:
    on_success: never
    on_failture: always
